name: Push Comment to PR
inputs:
  github-token:
    required: true
  pr-url:
    required: true
  report-url:
    required: false
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: |
        COMMIT_HASH=$(git show --format='%h' --no-patch)

        # コメントを生成
        cat << EOF > comments
        ## Test Report
        😊👍 PASS!!! 💯🎉
        (commit: ${COMMIT_HASH})

        The test report for this PR can be found at this URL.

        ${REPORT_URL}
        EOF

        # 過去のコメント数を取得
        USER=$(git config user.name | sed "s/\[.*\]//")  # 名前に[bot]がある場合は除去
        COMMENT_COUNT=$(gh pr view --json "comments" --jq ".comments.[] | select (.author.login == \"${USER}\") | .url" | wc -l)

        # コメントを送信
        # https://cli.github.com/manual/gh_pr_comment
        if [ "${COMMENT_COUNT}" -eq 0 ]; then
          gh pr comment "${PR_URL}" -F ./comments
        elif [ "${COMMENT_COUNT}" -eq 1 ]; then
          # "--edit-last"で最後のコミットを上書き
          gh pr comment "${PR_URL}" -F ./comments --edit-last
        else
          # 複数コメントがある場合はエラー
          echo "cannot edit because there are multiple comments. count = ${COMMENT_COUNT}"
          exit 1
        fi

      env:
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        # PR_URL: ${{ github.event.pull_request.html_url }}
        PR_URL: ${{ inputs.pr-url }}
        # PAGE_URL: ${{ steps.deployment.outputs.page_url }}
        # REPORT_OUTPUT_PATH: ${{ steps.generate_report_url.outputs.report_output_path }}
        REPORT_URL: ${{ inputs.report-url }}
